version: '3.9'
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "5050:5050"
    container_name: rtmp_server_test
    volumes:
      - ./data:/tmp/hls
      - ./data_rec:/tmp/rec
